context:
  name: jupyterlab-dyno
  version: "0.1.2"
  python_min: "3.12"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/EconForge/jupyterlab-dyno/archive/refs/tags/v${{ version }}.tar.gz
  sha256: a8143772a4285a3c19d665d7d004d7de3976bd0855689eb0fa2047fca66eda35

build:
  noarch: python
  number: 0
  script: pip install . --no-deps -vv --no-build-isolation --ignore-installed --no-index

requirements:
  host:
    - python ${{ python_min }}.*  
    - hatchling >=1.5.0
    - pip >=25.1.1,<26
    - nodejs >=24.4.0,<24.5
    - hatch-nodejs-version >=0.3.2
    - hatch-jupyter-builder >=0.5.0
    - jupyterlab >=4.0.0,<5
  run:
    - python >=${{ python_min }}
    - dyno >=0.1.12
    - xeus-python >=0.19

tests:
  - python:
      python_version:
        - ${{ python_min }}.*
        - "*"
      imports:
        - jupyterlab_dyno

about:
  homepage: https://github.com/EconForge/jupyterlab-dyno
  summary: jupyterlab-dyno
  description: A jupyterlab extension to solve .mod DSGE models using dyno.py
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - albop
